# Generated by Django 5.0.6 on 2024-06-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=55)),
                ('Last_Name', models.CharField(max_length=55)),
                ('Birthday', models.DateField()),
                ('Age', models.IntegerField()),
                ('Website', models.CharField(max_length=55)),
                ('City', models.CharField(max_length=55)),
                ('Email', models.CharField(max_length=55)),
                ('Short_Description', models.CharField(max_length=255)),
                ('Long_Description', models.CharField(max_length=555)),
            ],
        ),
    ]
