# Generated by Django 5.0.6 on 2024-06-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0002_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingSkils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill_Name', models.CharField(max_length=55)),
                ('How_Profotional', models.IntegerField()),
            ],
        ),
    ]
