# Generated by Django 5.0.6 on 2024-06-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0003_programmingskils'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=55)),
                ('Image', models.ImageField(upload_to='dinamic_img')),
            ],
        ),
        migrations.RenameField(
            model_name='programmingskils',
            old_name='Skill_Name',
            new_name='Name',
        ),
    ]
