# Generated by Django 5.0.6 on 2024-06-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0004_certificates_rename_skill_name_programmingskils_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('instagram', 'instagram'), ('telegram', 'telegram'), ('linkedin', 'linkedin'), ('github', 'github'), ('whatsapp', 'whatsapp'), ('twitter-x', 'twitter-x'), ('youtube', 'youtube'), ('threads', 'threads')], max_length=55)),
                ('Link', models.CharField(max_length=255)),
            ],
        ),
    ]
