# Generated by Django 5.0.2 on 2024-06-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0007_myimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=55)),
                ('Image', models.ImageField(upload_to='dinamic_img')),
                ('Link', models.CharField(max_length=255)),
            ],
        ),
    ]
