# Generated by Django 5.0.2 on 2024-06-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0008_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='dinamic_img'),
        ),
    ]
