# Generated by Django 5.0.2 on 2024-06-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0009_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Image',
            field=models.ImageField(default=1, upload_to='dinamic_img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='Link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
