# Generated by Django 5.0.2 on 2024-06-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0010_alter_project_image_alter_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Link',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
