# Generated by Django 5.0.2 on 2024-06-19 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0011_alter_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
