# Generated by Django 5.0.2 on 2024-06-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0012_sendemail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingskils',
            name='Show_Side',
            field=models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], default=1, max_length=55),
            preserve_default=False,
        ),
    ]
